version: '3.8'

services:
  maptile-preview:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: maptile-preview
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - maptile-network

  # Optional: Add a reverse proxy for production (uncomment if needed)
  # nginx-proxy:
  #   image: nginx:alpine
  #   container_name: nginx-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./proxy.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - maptile-preview
  #   restart: unless-stopped
  #   networks:
  #     - maptile-network

networks:
  maptile-network:
    driver: bridge